// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UCHAJANASHIA.FINAL.Data;

#nullable disable

namespace UCHAJANASHIA.FINAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240610075658_uca")]
    partial class uca
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UCHAJANASHIA.FINAL.Models.Cat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("Birhtday")
                        .HasColumnType("date");

                    b.Property<string>("Breed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cat");
                });

            modelBuilder.Entity("UCHAJANASHIA.FINAL.Models.Toy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("OwnerCatID")
                        .HasColumnType("int");

                    b.Property<string>("ToyColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("ToyWeight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("OwnerCatID");

                    b.ToTable("Toy");
                });

            modelBuilder.Entity("UCHAJANASHIA.FINAL.Models.Toy", b =>
                {
                    b.HasOne("UCHAJANASHIA.FINAL.Models.Cat", "OwnerCat")
                        .WithMany("CatToysList")
                        .HasForeignKey("OwnerCatID");

                    b.Navigation("OwnerCat");
                });

            modelBuilder.Entity("UCHAJANASHIA.FINAL.Models.Cat", b =>
                {
                    b.Navigation("CatToysList");
                });
#pragma warning restore 612, 618
        }
    }
}
